EAR: JackAdapter Class Reference
JackAdapter Class Reference
C++ Wrapper for the JACK Audio Connection Kit client API.
#include <jackadapter.h>
Signals
void error (const QString &errorMessage)
Public Member Functions
bool connectToServer (QString name)
void registerStereoInputPort (QString label)
void registerStereoOutputPort (QString label)
void setProcessor (Processor *processor)
void startAudioProcessing ()
void stopAudioProcessing ()
int sampleRate ()
int bufferSize ()
float cpuLoad ()
StereoPort stereoInputPort (QString label)
StereoPort stereoOutputPort (QString label)
Static Public Member Functions
static JackAdapter * instance ()
Detailed Description
C++ Wrapper for the JACK Audio Connection Kit client API.
Author:
Jacob Dawid (jacob.dawid@cybercatalyst.net)
Otto Ritter (otto.ritter.or@googlemail.com)
Date:
09.2011
This class wraps a singleton around the C API of JACK in order to provide some additional features. Since it derives from QObject it can be integrated into Qt's signals and slots system. Also, it includes a few routines to simplify the integration of fftw.
Definition at line 114 of file jackadapter.h.
Member Function Documentation
int JackAdapter::bufferSize ()
Returns the current sample buffer size.
Returns:
Buffer size in samples.
Definition at line 75 of file jackadapter.cpp.
bool JackAdapter::connectToServer (QString name)
This method attempts to connect to the audio server.
Parameters:
name Name that will be used to register this application as a client.
Definition at line 47 of file jackadapter.cpp.
References jack_client_open(), jack_set_buffer_size_callback(), jack_set_error_function(), jack_set_info_function(), jack_set_process_callback(), jack_set_sample_rate_callback(), and JackNullOption.
float JackAdapter::cpuLoad ()
Returns the current CPU load in percent.
Definition at line 79 of file jackadapter.cpp.
References jack_cpu_load().
void JackAdapter::error (const QString & errorMessage) [signal]
This signal will be emitted when an error occurs.
JackAdapter * JackAdapter::instance () [static]
Returns the instance for this singleton.
Definition at line 43 of file jackadapter.cpp.
Referenced by MainWindow::closeEvent(), EarProcessor::EarProcessor(), and MainWindow::MainWindow().
void JackAdapter::registerStereoInputPort (QString label)
Tries to register a new stereo input port.
Parameters:
label Name that will be used to register this port.
Definition at line 91 of file jackadapter.cpp.
References JACK_DEFAULT_AUDIO_TYPE, and jack_port_register().
Referenced by EarProcessor::EarProcessor().
void JackAdapter::registerStereoOutputPort (QString label)
Tries to register a new stereo output port.
Parameters:
label Name that will be used to register this port.
Definition at line 102 of file jackadapter.cpp.
References JACK_DEFAULT_AUDIO_TYPE, and jack_port_register().
Referenced by EarProcessor::EarProcessor().
int JackAdapter::sampleRate ()
Returns the current sample rate.
Returns:
Sample rate in Hz.
Definition at line 71 of file jackadapter.cpp.
void JackAdapter::setProcessor (Processor * processor)
Assigns a processor that will handle audio processing.
Parameters:
processor The processor that will handle audio processing.
Definition at line 113 of file jackadapter.cpp.
Referenced by MainWindow::MainWindow().
void JackAdapter::startAudioProcessing ()
Activates audio processing.
Definition at line 61 of file jackadapter.cpp.
References jack_activate().
Referenced by MainWindow::MainWindow().
StereoPort JackAdapter::stereoInputPort (QString label)
Returns the input stereo port associated with this label.
Parameters:
label Name of the stereo port.
Returns:
Stereo port that has been requested.
Definition at line 83 of file jackadapter.cpp.
StereoPort JackAdapter::stereoOutputPort (QString label)
Returns the output stereo port associated with this label.
Parameters:
label Name of the stereo port.
Returns:
Stereo port that has been requested.
Definition at line 87 of file jackadapter.cpp.
void JackAdapter::stopAudioProcessing ()
Deactivates audio processing and disconnects from the audio server.
Definition at line 67 of file jackadapter.cpp.
References jack_deactivate().
Referenced by MainWindow::closeEvent().
The documentation for this class was generated from the following files:
libear/include/jackadapter.h
libear/src/jackadapter.cpp