EAR: PRBSGenerator Class Reference
PRBSGenerator Class Reference
#include <prbsgenerator.h>
Public Types
enum {
G7 = 0x00000041, G8 = 0x0000008E, G15 = 0x00004001, G16 = 0x00008016,
G23 = 0x00400010, G24 = 0x0080000D, G31 = 0x40000004, G32 = 0x80000057
}
Public Member Functions
PRBSGenerator (void)
void setPoly (uint32_t poly)
void setStat (uint32_t stat)
void sync_forw (uint32_t bits)
void sync_back (uint32_t bits)
int step (void)
void crc_in (int b)
int crc_out (void)
uint32_t stat (void) const
uint32_t poly (void) const
uint32_t mask (void) const
uint32_t hbit (void) const
int degr (void) const
~PRBSGenerator (void)
Detailed Description
Definition at line 102 of file prbsgenerator.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
G7
G8
G15
G16
G23
G24
G31
G32
Definition at line 106 of file prbsgenerator.h.
Constructor & Destructor Documentation
PRBSGenerator::PRBSGenerator (void) [inline]
Definition at line 149 of file prbsgenerator.h.
PRBSGenerator::~PRBSGenerator (void) [inline]
Definition at line 155 of file prbsgenerator.h.
Member Function Documentation
void PRBSGenerator::crc_in (int b) [inline]
Definition at line 230 of file prbsgenerator.h.
int PRBSGenerator::crc_out (void) [inline]
Definition at line 242 of file prbsgenerator.h.
int PRBSGenerator::degr (void) const [inline]
Definition at line 262 of file prbsgenerator.h.
uint32_t PRBSGenerator::hbit (void) const [inline]
Definition at line 260 of file prbsgenerator.h.
uint32_t PRBSGenerator::mask (void) const [inline]
Definition at line 258 of file prbsgenerator.h.
uint32_t PRBSGenerator::poly (void) const [inline]
Definition at line 256 of file prbsgenerator.h.
Referenced by setPoly().
void PRBSGenerator::setPoly (uint32_t poly) [inline]
Definition at line 160 of file prbsgenerator.h.
References poly().
Referenced by RandomGenerator::init().
void PRBSGenerator::setStat (uint32_t stat) [inline]
Definition at line 178 of file prbsgenerator.h.
Referenced by RandomGenerator::init().
uint32_t PRBSGenerator::stat (void) const [inline]
Definition at line 254 of file prbsgenerator.h.
Referenced by RandomGenerator::init().
int PRBSGenerator::step (void) [inline]
Definition at line 188 of file prbsgenerator.h.
Referenced by RandomGenerator::init().
void PRBSGenerator::sync_back (uint32_t bits) [inline]
Definition at line 215 of file prbsgenerator.h.
void PRBSGenerator::sync_forw (uint32_t bits) [inline]
Definition at line 202 of file prbsgenerator.h.
The documentation for this class was generated from the following file:
libear/include/jnoise/prbsgenerator.h