EAR: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
Protected Member Functions
void closeEvent (QCloseEvent *closeEvent)
Detailed Description
Author:
Jacob Dawid (jacob.dawid@cybercatalyst.net)
Otto Ritter (otto.ritter.or@googlemail.com)
Date:
09.2011
Main window for the whole application.
Definition at line 46 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) [explicit]
Definition at line 33 of file mainwindow.cpp.
References JackAdapter::instance(), MUSIC_COMBO_TEXT, PINK_NOISE_COMBO_TEXT, JackAdapter::setProcessor(), JackAdapter::startAudioProcessing(), and WHITE_NOISE_COMBO_TEXT.
MainWindow::~MainWindow ()
Definition at line 75 of file mainwindow.cpp.
Member Function Documentation
void MainWindow::closeEvent (QCloseEvent * closeEvent) [protected]
Reimplemented from QWidget.
Definition at line 79 of file mainwindow.cpp.
References JackAdapter::instance(), and JackAdapter::stopAudioProcessing().
The documentation for this class was generated from the following files:
gui/include/mainwindow.h
gui/src/mainwindow.cpp