EAR: VisualizerWidget Class Reference
VisualizerWidget Class Reference
View counterpart for the EAR processor. This class is the view counterpart for the EAR processor, which acts as the model class.
#include <visualizerwidget.h>
Public Member Functions
VisualizerWidget (EarProcessor *earProcessor, QWidget *parent=0)
Protected Member Functions
void initializeGL ()
void resizeGL (int w, int h)
void paintGL ()
void wheelEvent (QWheelEvent *wheelEvent)
void mousePressEvent (QMouseEvent *mouseEvent)
void mouseReleaseEvent (QMouseEvent *mouseEvent)
void mouseMoveEvent (QMouseEvent *mouseEvent)
Detailed Description
View counterpart for the EAR processor. This class is the view counterpart for the EAR processor, which acts as the model class.
Definition at line 17 of file visualizerwidget.h.
Constructor & Destructor Documentation
VisualizerWidget::VisualizerWidget (EarProcessor * earProcessor, QWidget * parent = 0)
Constructs a new view that will be attached to the given EAR processor.
Parameters:
earProcessor EAR processor to which this view will be attached.
parent Parent widget for the Qt framework.
Definition at line 5 of file visualizerwidget.cpp.
Member Function Documentation
void VisualizerWidget::initializeGL () [protected]
Reimplemented from QGLWidget.
Definition at line 26 of file visualizerwidget.cpp.
void VisualizerWidget::mouseMoveEvent (QMouseEvent * mouseEvent) [protected]
Reimplemented from QGLWidget
Parameters:
mouseEvent Mouse event.
Definition at line 242 of file visualizerwidget.cpp.
void VisualizerWidget::mousePressEvent (QMouseEvent * mouseEvent) [protected]
Reimplemented from QGLWidget.
Parameters:
mouseEvent Mouse event.
Definition at line 229 of file visualizerwidget.cpp.
void VisualizerWidget::mouseReleaseEvent (QMouseEvent * mouseEvent) [protected]
Reimplemented from QGLWidget.
Parameters:
mouseEvent Mouse event.
Definition at line 235 of file visualizerwidget.cpp.
void VisualizerWidget::paintGL () [protected]
Reimplemented from QGLWidget.
Definition at line 43 of file visualizerwidget.cpp.
References DigitalEqualizer::acquireControls(), DigitalEqualizer::controls(), EarProcessor::leftEqualizer(), DigitalEqualizer::releaseControls(), and EarProcessor::rightEqualizer().
void VisualizerWidget::resizeGL (int w, int h) [protected]
Reimplemented from QGLWidget.
Parameters:
w Width of the new OpenGL viewport.
h Height of the new OpenGL viewport.
Definition at line 35 of file visualizerwidget.cpp.
void VisualizerWidget::wheelEvent (QWheelEvent * wheelEvent) [protected]
Reimplemented from QGLWidget.
Parameters:
wheelEvent Wheel event.
Definition at line 217 of file visualizerwidget.cpp.
The documentation for this class was generated from the following files:
gui/include/visualizerwidget.h
gui/src/visualizerwidget.cpp