EAR: RandomGenerator Class Reference
RandomGenerator Class Reference
#include <randomgenerator.h>
Public Member Functions
RandomGenerator (void)
void init (uint32_t s)
uint32_t irand (void)
double urand (void)
double grand (void)
void grand (double *x, double *y)
float urandf (void)
float grandf (void)
void grandf (float *x, float *y)
~RandomGenerator (void)
RandomGenerator (const RandomGenerator &)
RandomGenerator & operator= (const RandomGenerator &)
Detailed Description
Definition at line 27 of file randomgenerator.h.
Constructor & Destructor Documentation
RandomGenerator::RandomGenerator (void)
Definition at line 33 of file randomgenerator.cpp.
References init().
RandomGenerator::~RandomGenerator (void)
Definition at line 39 of file randomgenerator.cpp.
RandomGenerator::RandomGenerator (const RandomGenerator &)
Member Function Documentation
double RandomGenerator::grand (void)
Definition at line 68 of file randomgenerator.cpp.
References irand().
void RandomGenerator::grand (double * x, double * y)
Definition at line 94 of file randomgenerator.cpp.
References irand().
float RandomGenerator::grandf (void)
Definition at line 112 of file randomgenerator.cpp.
References irand().
Referenced by JNoise::JNoise().
void RandomGenerator::grandf (float * x, float * y)
Definition at line 138 of file randomgenerator.cpp.
References irand().
void RandomGenerator::init (uint32_t s)
Definition at line 44 of file randomgenerator.cpp.
References PRBSGenerator::G32, PRBSGenerator::setPoly(), PRBSGenerator::setStat(), PRBSGenerator::stat(), and PRBSGenerator::step().
Referenced by JNoise::JNoise(), and RandomGenerator().
uint32_t RandomGenerator::irand (void) [inline]
Definition at line 35 of file randomgenerator.h.
Referenced by grand(), grandf(), JNoise::process(), urand(), and urandf().
RandomGenerator& RandomGenerator::operator= (const RandomGenerator &)
double RandomGenerator::urand (void) [inline]
Definition at line 45 of file randomgenerator.h.
References irand().
float RandomGenerator::urandf (void) [inline]
Definition at line 48 of file randomgenerator.h.
References irand().
The documentation for this class was generated from the following files:
libear/include/jnoise/randomgenerator.h
libear/src/jnoise/randomgenerator.cpp