EAR: EarProcessor Class Reference
EarProcessor Class Reference
EarProcessor performs the central task of audio processing.
#include <earprocessor.h>
Data Structures
struct Calibration
Public Types
enum OperationMode { CalibratingLatency, ProcessingAudio }
enum SignalSource { ExternalSource, WhiteNoise, PinkNoise }
enum Channel { LeftChannel = 0, RightChannel = 1 }
Public Slots
void calibrate ()
void setModeToRectification ()
void setAutomaticAdaptionActive (bool on)
void setBypassActive (bool on)
Signals
void calibrationFinished ()
Public Member Functions
EarProcessor ()
~EarProcessor ()
DigitalEqualizer * leftEqualizer ()
DigitalEqualizer * rightEqualizer ()
void setSignalSource (SignalSource signalSource)
SignalSource signalSource ()
bool automaticAdaptionActive ()
bool bypassActive ()
int microphoneLevelLeft ()
int microphoneLevelRight ()
int signalSourceLevelLeft ()
int signalSourceLevelRight ()
void process (int samples)
int leftLatency ()
int rightLatency ()
Detailed Description
EarProcessor performs the central task of audio processing.
Author:
Jacob Dawid (jacob.dawid@cybercatalyst.net)
Otto Ritter (otto.ritter.or@googlemail.com)
Date:
09.2011
The EAR processor compares the incoming delayed reference signal with the recorded signal usually obtained by the microphone. In order to compensate the differences in the the frequency spectrum it uses two independent equalizers.
Definition at line 50 of file earprocessor.h.
Member Enumeration Documentation
enum EarProcessor::Channel
Signal channels.
Enumerator:
LeftChannel
RightChannel
Definition at line 68 of file earprocessor.h.
enum EarProcessor::OperationMode
Operating modes.
Enumerator:
CalibratingLatency
ProcessingAudio
Definition at line 55 of file earprocessor.h.
enum EarProcessor::SignalSource
Different kinds of signal sources.
Enumerator:
ExternalSource
WhiteNoise
PinkNoise
Definition at line 61 of file earprocessor.h.
Constructor & Destructor Documentation
EarProcessor::EarProcessor ()
Constructs a new EarProcessor.
Definition at line 29 of file earprocessor.cpp.
References calibrationFinished(), ExternalSource, JackAdapter::instance(), ProcessingAudio, JackAdapter::registerStereoInputPort(), and JackAdapter::registerStereoOutputPort().
EarProcessor::~EarProcessor ()
Destructor.
Definition at line 65 of file earprocessor.cpp.
Member Function Documentation
bool EarProcessor::automaticAdaptionActive ()
Returns true, when the automatic adaption is active.
Definition at line 89 of file earprocessor.cpp.
bool EarProcessor::bypassActive ()
Returns true, when the signal is being bypassed.
Definition at line 94 of file earprocessor.cpp.
void EarProcessor::calibrate () [slot]
Resets the calibration.
Definition at line 471 of file earprocessor.cpp.
References CalibratingLatency.
void EarProcessor::calibrationFinished () [signal]
This signal is emitted when the calibration finished.
Referenced by EarProcessor().
DigitalEqualizer * EarProcessor::leftEqualizer ()
Returns a pointer to the equalizer object for the left channel.
Definition at line 71 of file earprocessor.cpp.
Referenced by VisualizerWidget::paintGL().
int EarProcessor::leftLatency () [inline]
Provides the latency for the left channel.
Returns:
Latency measured in number of samples.
See also:
EarProcessor::processCalibration(int samples)
Definition at line 120 of file earprocessor.h.
int EarProcessor::microphoneLevelLeft ()
Returns the average microphone amplitude for the left channel.
Definition at line 176 of file earprocessor.cpp.
References LeftChannel.
int EarProcessor::microphoneLevelRight ()
Returns the average microphone amplitude for the right channel.
Definition at line 181 of file earprocessor.cpp.
References RightChannel.
void EarProcessor::process (int samples) [virtual]
Reimplemented from process. This will be called whenever there are new samples available for processing. Attention: This method is time critical.
Parameters:
samples Number of samples that are available.
Implements Processor.
Definition at line 196 of file earprocessor.cpp.
References CalibratingLatency, and ProcessingAudio.
DigitalEqualizer * EarProcessor::rightEqualizer ()
Returns a pointer to the equalizer object for the right channel.
Definition at line 75 of file earprocessor.cpp.
Referenced by VisualizerWidget::paintGL().
int EarProcessor::rightLatency () [inline]
Provides the latency for the right channel.
Returns:
Latency measured in number of samples.
See also:
EarProcessor::processCalibration(int samples)
Definition at line 127 of file earprocessor.h.
void EarProcessor::setAutomaticAdaptionActive (bool on) [slot]
Activates/deactivates automatic adaption.
Definition at line 489 of file earprocessor.cpp.
void EarProcessor::setBypassActive (bool on) [slot]
Activates/deactivates bypassing.
Definition at line 494 of file earprocessor.cpp.
void EarProcessor::setModeToRectification () [slot]
Set mode to "Rectification".
Definition at line 480 of file earprocessor.cpp.
References ProcessingAudio.
void EarProcessor::setSignalSource (SignalSource signalSource)
Immediately sets the signal source to use.
Definition at line 79 of file earprocessor.cpp.
References signalSource().
EarProcessor::SignalSource EarProcessor::signalSource ()
Returns the the signal source that is used for processing.
Definition at line 84 of file earprocessor.cpp.
Referenced by setSignalSource().
int EarProcessor::signalSourceLevelLeft ()
Returns the average signal source amplitude for the left channel.
Definition at line 186 of file earprocessor.cpp.
References LeftChannel.
int EarProcessor::signalSourceLevelRight ()
Returns the average signal source amplitude for the right channel.
Definition at line 191 of file earprocessor.cpp.
References RightChannel.
The documentation for this class was generated from the following files:
libear/include/earprocessor.h
libear/src/earprocessor.cpp